// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(TestdbContext))]
    [Migration("20230828080210_InitTestDB")]
    partial class InitTestDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsShowOnHome")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SeoAlias")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22a96002-14f2-4ef3-a820-3f9c1be5f62f"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4741),
                            DisplayName = "Hạt Macca",
                            IsShowOnHome = true,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam",
                            MetaKeyword = "Hạt Macca",
                            MetaTitle = "Hạt Macca",
                            Name = "Hạt Macca",
                            SeoAlias = "hat-macca",
                            SortOrder = 1,
                            Status = 1,
                            UrlCode = "hat-macca"
                        },
                        new
                        {
                            Id = new Guid("59a89bce-2444-4061-8b3a-5e67b3cd5abd"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4751),
                            DisplayName = "Hạnh nhân",
                            IsShowOnHome = true,
                            MetaDescription = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột hoặc bột nhão. Trong 28 gram hạnh nhân có chứa hàm lượng chất",
                            MetaKeyword = "Hạnh nhân",
                            MetaTitle = "Hạnh nhân",
                            Name = "Hạnh nhân",
                            SeoAlias = "hanh-nhan",
                            SortOrder = 2,
                            Status = 1,
                            UrlCode = "hanh-nhan"
                        },
                        new
                        {
                            Id = new Guid("afa34fd5-d333-41b7-b65b-265fbae5bbd4"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4755),
                            DisplayName = "Mix hạt dinh dưỡng",
                            IsShowOnHome = true,
                            MetaDescription = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay.",
                            MetaKeyword = "Mix hạt dinh dưỡng",
                            MetaTitle = "Mix hạt dinh dưỡng",
                            Name = "Mix hạt dinh dưỡng",
                            SeoAlias = "mix-ha",
                            SortOrder = 3,
                            Status = 1,
                            UrlCode = "mix-hat"
                        },
                        new
                        {
                            Id = new Guid("de547052-407b-4d21-b85d-8f534ce021b0"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4757),
                            DisplayName = "Granola",
                            IsShowOnHome = true,
                            MetaDescription = "Granola",
                            MetaKeyword = "Granola",
                            MetaTitle = "Granola",
                            Name = "Granola",
                            SeoAlias = "granola",
                            SortOrder = 4,
                            Status = 1,
                            UrlCode = "granola"
                        },
                        new
                        {
                            Id = new Guid("8cea4866-3bb6-4c8c-a2b6-d5de042c8eb3"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4763),
                            DisplayName = "Hạt óc chó",
                            IsShowOnHome = true,
                            MetaDescription = "Hạt óc chó",
                            MetaKeyword = "Hạt óc chó",
                            MetaTitle = "Hạt óc chó",
                            Name = "Hạt óc chó",
                            SeoAlias = "hat-oc-cho",
                            SortOrder = 5,
                            Status = 1,
                            UrlCode = "hat-oc-cho"
                        },
                        new
                        {
                            Id = new Guid("db90c84a-2f4d-4a14-b819-a2cd0a11780b"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4766),
                            DisplayName = "Hạt điều",
                            IsShowOnHome = true,
                            MetaDescription = "Hạt điều",
                            MetaKeyword = "Hạt điều",
                            MetaTitle = "Hạt điều",
                            Name = "Hạt điều",
                            SeoAlias = "hat-dieu",
                            SortOrder = 6,
                            Status = 1,
                            UrlCode = "hat-dieu"
                        });
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("IsBestSeller")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SeoAlias")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Sku")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id", "Name", "Sku", "UrlCode");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7dcee8ad-4239-4ba4-9ec3-6fe34c815d70"),
                            CategoryId = new Guid("22a96002-14f2-4ef3-a820-3f9c1be5f62f"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4925),
                            Description = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            Discount = 10000.0,
                            DisplayName = "Hạt Macca nhân nguyên",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            MetaKeyword = "Hạt Macca nhân vỡ",
                            MetaTitle = "Hạt Macca nhân vỡ",
                            Name = "Hạt Macca nhân vỡ",
                            OriginalPrice = 145000.0,
                            Price = 135000.0,
                            SeoAlias = "hat-macca-nhan-vo",
                            Sku = "M01",
                            Status = 1,
                            UrlCode = "hat-macca"
                        },
                        new
                        {
                            Id = new Guid("28e1e5fe-8460-4d9d-a3c0-75fc3ee83c24"),
                            CategoryId = new Guid("22a96002-14f2-4ef3-a820-3f9c1be5f62f"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4935),
                            Description = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            Discount = 5000.0,
                            DisplayName = "Hạt Macca nhân nguyên",
                            IsBestSeller = false,
                            IsFeatured = false,
                            IsNew = false,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            MetaKeyword = "Hạt Macca nhân nguyên",
                            MetaTitle = "Hạt Macca nhân nguyên",
                            Name = "Hạt Macca nhân nguyên",
                            OriginalPrice = 165000.0,
                            Price = 160000.0,
                            SeoAlias = "hat-macca-nhan-nguyen",
                            Sku = "M02",
                            Status = 1,
                            UrlCode = "hat-macca-nhan-nguyen"
                        },
                        new
                        {
                            Id = new Guid("9a856dac-516b-4c8a-b801-96743fd91c55"),
                            CategoryId = new Guid("22a96002-14f2-4ef3-a820-3f9c1be5f62f"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4990),
                            Description = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            Discount = 5000.0,
                            DisplayName = "Hạt Macca nứt vỏ",
                            IsBestSeller = false,
                            IsFeatured = false,
                            IsNew = false,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            MetaKeyword = "Hạt Macca nứt vỏ",
                            MetaTitle = "Hạt Macca nứt vỏ",
                            Name = "Hạt Macca nứt vỏ (size lớn)",
                            OriginalPrice = 130000.0,
                            Price = 125000.0,
                            SeoAlias = "hat-macca-nut-vo",
                            Sku = "M03",
                            Status = 1,
                            UrlCode = "hat-macca-nut-vo"
                        },
                        new
                        {
                            Id = new Guid("bb0a5050-035a-4fee-a307-4b47c5b11080"),
                            CategoryId = new Guid("22a96002-14f2-4ef3-a820-3f9c1be5f62f"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(4997),
                            Description = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            Discount = 5000.0,
                            DisplayName = "Hạt Macca nứt vỏ",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            MetaKeyword = "Hạt Macca nứt vỏ",
                            MetaTitle = "Hạt Macca nứt vỏ",
                            Name = "Hạt Macca nứt vỏ (size nhỏ)",
                            OriginalPrice = 100000.0,
                            Price = 95000.0,
                            SeoAlias = "hat-macca-nut-vo",
                            Sku = "M04",
                            Status = 1,
                            UrlCode = "hat-macca-nut-vo"
                        },
                        new
                        {
                            Id = new Guid("072c4483-d304-419b-a7e5-dac21f5ab0c2"),
                            CategoryId = new Guid("afa34fd5-d333-41b7-b65b-265fbae5bbd4"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(5002),
                            Description = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay. ",
                            Discount = 10000.0,
                            DisplayName = "MIX HẠT CAO CẤP",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay. ",
                            MetaKeyword = "MIX HẠT CAO CẤP",
                            MetaTitle = "MIX HẠT CAO CẤP",
                            Name = "MIX HẠT CAO CẤP",
                            OriginalPrice = 170000.0,
                            Price = 160000.0,
                            SeoAlias = "mix-hat-cao-cap",
                            Sku = "MIX01",
                            Status = 1,
                            UrlCode = "mix-hat-cao-cap"
                        },
                        new
                        {
                            Id = new Guid("d345fd72-4d30-4c39-8797-8df2860f08fc"),
                            CategoryId = new Guid("afa34fd5-d333-41b7-b65b-265fbae5bbd4"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(5007),
                            Description = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay. ",
                            Discount = 10000.0,
                            DisplayName = "MIX 6 LOẠI HẠT DINH DƯỠNG",
                            IsBestSeller = false,
                            IsFeatured = false,
                            IsNew = true,
                            MetaDescription = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay. ",
                            MetaKeyword = "MIX 6 LOẠI HẠT DINH DƯỠNG",
                            MetaTitle = "MIX 6 LOẠI HẠT DINH DƯỠNG",
                            Name = "MIX 6 LOẠI HẠT DINH DƯỠNG",
                            OriginalPrice = 160000.0,
                            Price = 150000.0,
                            SeoAlias = "mix-6-loai-hat-dinh-duong",
                            Sku = "MIX02",
                            Status = 1,
                            UrlCode = "mix-6-loai-hat-dinh-duong"
                        },
                        new
                        {
                            Id = new Guid("2a8aa21f-8dfe-4285-b2d0-6b64980a3c2d"),
                            CategoryId = new Guid("59a89bce-2444-4061-8b3a-5e67b3cd5abd"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(5013),
                            Description = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột...",
                            Discount = 5000.0,
                            DisplayName = "HẠNH NHÂN RANG BƠ",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột...",
                            MetaKeyword = "HẠNH NHÂN RANG BƠ",
                            MetaTitle = "HẠNH NHÂN RANG BƠ",
                            Name = "HẠNH NHÂN RANG BƠ",
                            OriginalPrice = 130000.0,
                            Price = 125000.0,
                            SeoAlias = "hanh-nhan-rang-bo",
                            Sku = "H01",
                            Status = 1,
                            UrlCode = "hanh-nhan-rang-bo"
                        },
                        new
                        {
                            Id = new Guid("a5413d2e-7c1a-43fc-b8b3-cac4603c9485"),
                            CategoryId = new Guid("59a89bce-2444-4061-8b3a-5e67b3cd5abd"),
                            CreatedOn = new DateTime(2023, 8, 28, 8, 2, 10, 700, DateTimeKind.Utc).AddTicks(5017),
                            Description = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột...",
                            Discount = 5000.0,
                            DisplayName = "HẠNH NHÂN SẤY",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột...",
                            MetaKeyword = "HẠNH NHÂN SẤY",
                            MetaTitle = "HẠNH NHÂN SẤY",
                            Name = "HẠNH NHÂN SẤY",
                            OriginalPrice = 135000.0,
                            Price = 130000.0,
                            SeoAlias = "hanh-nhan-say",
                            Sku = "H02",
                            Status = 1,
                            UrlCode = "hanh-nhan-say"
                        });
                });

            modelBuilder.Entity("Core.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("sizes", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Slide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("slides", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.ProductImage", b =>
                {
                    b.HasOne("Core.Entities.Product", null)
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Core.Entities.Size", b =>
                {
                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
