// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(TestdbContext))]
    partial class TestdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsShowOnHome")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SeoAlias")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f17239b-a420-4597-8cbd-0c188e1d4ada"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(8962),
                            DisplayName = "Hạt Macca",
                            IsShowOnHome = true,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam",
                            MetaKeyword = "Hạt Macca",
                            MetaTitle = "Hạt Macca",
                            Name = "Hạt Macca",
                            SeoAlias = "hat-macca",
                            SortOrder = 1,
                            Status = 1,
                            UrlCode = "hat-macca"
                        },
                        new
                        {
                            Id = new Guid("0e6b14eb-242d-46ec-b90b-75559c14df26"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(8975),
                            DisplayName = "Hạnh nhân",
                            IsShowOnHome = true,
                            MetaDescription = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột hoặc bột nhão. Trong 28 gram hạnh nhân có chứa hàm lượng chất",
                            MetaKeyword = "Hạnh nhân",
                            MetaTitle = "Hạnh nhân",
                            Name = "Hạnh nhân",
                            SeoAlias = "hanh-nhan",
                            SortOrder = 2,
                            Status = 1,
                            UrlCode = "hanh-nhan"
                        },
                        new
                        {
                            Id = new Guid("d3a7f832-fb28-4458-97b4-90d0bb61b622"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(8978),
                            DisplayName = "Mix hạt dinh dưỡng",
                            IsShowOnHome = true,
                            MetaDescription = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay.",
                            MetaKeyword = "Mix hạt dinh dưỡng",
                            MetaTitle = "Mix hạt dinh dưỡng",
                            Name = "Mix hạt dinh dưỡng",
                            SeoAlias = "mix-ha",
                            SortOrder = 3,
                            Status = 1,
                            UrlCode = "mix-hat"
                        },
                        new
                        {
                            Id = new Guid("6c5d6237-94b0-47bb-9f2c-1f4d89e74043"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(8980),
                            DisplayName = "Granola",
                            IsShowOnHome = true,
                            MetaDescription = "Granola",
                            MetaKeyword = "Granola",
                            MetaTitle = "Granola",
                            Name = "Granola",
                            SeoAlias = "granola",
                            SortOrder = 4,
                            Status = 1,
                            UrlCode = "granola"
                        },
                        new
                        {
                            Id = new Guid("2ba2070c-d658-4348-a490-d22c1baaed75"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(8983),
                            DisplayName = "Hạt óc chó",
                            IsShowOnHome = true,
                            MetaDescription = "Hạt óc chó",
                            MetaKeyword = "Hạt óc chó",
                            MetaTitle = "Hạt óc chó",
                            Name = "Hạt óc chó",
                            SeoAlias = "hat-oc-cho",
                            SortOrder = 5,
                            Status = 1,
                            UrlCode = "hat-oc-cho"
                        },
                        new
                        {
                            Id = new Guid("030bfb43-c2d2-4921-9cdf-6109caa104cb"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(8985),
                            DisplayName = "Hạt điều",
                            IsShowOnHome = true,
                            MetaDescription = "Hạt điều",
                            MetaKeyword = "Hạt điều",
                            MetaTitle = "Hạt điều",
                            Name = "Hạt điều",
                            SeoAlias = "hat-dieu",
                            SortOrder = 6,
                            Status = 1,
                            UrlCode = "hat-dieu"
                        },
                        new
                        {
                            Id = new Guid("7e6e5f6f-9f18-42fb-91ff-418e09261fb4"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(8991),
                            DisplayName = "Bánh kẹp hạt dinh dưỡng",
                            IsShowOnHome = true,
                            MetaDescription = "Bánh kẹp hạt dinh dưỡng",
                            MetaKeyword = "Bánh kẹp hạt dinh dưỡng",
                            MetaTitle = "Bánh kẹp hạt dinh dưỡng",
                            Name = "Bánh kẹp hạt dinh dưỡng",
                            SeoAlias = "banh-kep-hat-dinh-duong",
                            SortOrder = 7,
                            Status = 1,
                            UrlCode = "banh-kep-hat-dinh-duong"
                        });
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2048)");

                    b.Property<double>("Discount")
                        .HasColumnType("double precision");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("IsBestSeller")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("MetaKeyword")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SeoAlias")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Sku")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrlCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id", "Name", "Sku", "UrlCode");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6fe5001c-0cc9-4873-a826-81676479ec52"),
                            CategoryId = new Guid("3f17239b-a420-4597-8cbd-0c188e1d4ada"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9217),
                            Description = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            Discount = 20000.0,
                            DisplayName = "Hạt Macca nhân nguyên",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            MetaKeyword = "Hạt Macca nhân vỡ",
                            MetaTitle = "Hạt Macca nhân vỡ",
                            Name = "Hạt Macca nhân vỡ",
                            OriginalPrice = 290000.0,
                            Price = 270000.0,
                            SeoAlias = "hat-macca-nhan-vo",
                            Sku = "M01",
                            Status = 1,
                            UrlCode = "hat-macca"
                        },
                        new
                        {
                            Id = new Guid("31b72883-ee9d-45b7-9770-51f4d7d2ba2f"),
                            CategoryId = new Guid("3f17239b-a420-4597-8cbd-0c188e1d4ada"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9226),
                            Description = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            Discount = 10000.0,
                            DisplayName = "Hạt Macca nhân nguyên",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            MetaKeyword = "Hạt Macca nhân nguyên",
                            MetaTitle = "Hạt Macca nhân nguyên",
                            Name = "Hạt Macca nhân nguyên",
                            OriginalPrice = 330000.0,
                            Price = 320000.0,
                            SeoAlias = "hat-macca-nhan-nguyen",
                            Sku = "M02",
                            Status = 1,
                            UrlCode = "hat-macca-nhan-nguyen"
                        },
                        new
                        {
                            Id = new Guid("4f4055a6-eb23-41c5-b885-1672c207e273"),
                            CategoryId = new Guid("3f17239b-a420-4597-8cbd-0c188e1d4ada"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9230),
                            Description = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            Discount = 5000.0,
                            DisplayName = "Hạt Macca nứt vỏ (size A)",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            MetaKeyword = "Hạt Macca nứt vỏ (size A)",
                            MetaTitle = "Hạt Macca nứt vỏ (size A)",
                            Name = "Hạt Macca nứt vỏ (A)",
                            OriginalPrice = 130000.0,
                            Price = 125000.0,
                            SeoAlias = "hat-macca-nut-vo-size-a",
                            Sku = "M03",
                            Status = 1,
                            UrlCode = "hat-macca-nut-vo-size-a"
                        },
                        new
                        {
                            Id = new Guid("c09653ee-9781-4b47-b1b9-23975c147bc5"),
                            CategoryId = new Guid("3f17239b-a420-4597-8cbd-0c188e1d4ada"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9234),
                            Description = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            Discount = 5000.0,
                            DisplayName = "Hạt Macca nứt vỏ (size B)",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = true,
                            MetaDescription = "Hạt Macca là hạt giống của cây macadamia, có nguồn gốc từ Úc và được trồng ở nhiều nơi trên thế giới, chằng hạn như Brazil, Costa Rica, Hawaii, New Zealand, trong đó có Việt Nam...\r\n                    Đây được xem là nữ hoàng của các loại hạt vì rất giàu dinh dưỡng, phù hợp với mọi lứa tuổi. Hạt mắc ca có hình cầu khoảng 20-30mm, hương thơm, vị béo ngậy đặc trưng...\r\n                    Tất cả các hạt đều đã được sấy giòn được tách vỏ chỉ còn nhân trắng nguyên bên trong giữ được 100% vị ngon tự nhiên.",
                            MetaKeyword = "Hạt Macca nứt vỏ (size B)",
                            MetaTitle = "Hạt Macca nứt vỏ (size B)",
                            Name = "Hạt Macca nứt vỏ (B)",
                            OriginalPrice = 100000.0,
                            Price = 95000.0,
                            SeoAlias = "hat-macca-nut-vo-size-b",
                            Sku = "M04",
                            Status = 1,
                            UrlCode = "hat-macca-nut-vo-size-b"
                        },
                        new
                        {
                            Id = new Guid("02306207-f983-4bcc-b7ec-70221cee8dc7"),
                            CategoryId = new Guid("d3a7f832-fb28-4458-97b4-90d0bb61b622"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9240),
                            Description = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay. Mix 5 loại hạt gồm Óc chó đỏ, Hạnh Nhân, Hạt điều, Óc chó vàng, Macca mang đến cho bạn nguồn dinh dưỡng tự nhiên, đa dạng. ",
                            Discount = 10000.0,
                            DisplayName = "MIX hạt cao cấp",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = true,
                            MetaDescription = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay. Mix 5 loại hạt gồm Óc chó đỏ, Hạnh Nhân, Hạt điều, Óc chó vàng, Macca mang đến cho bạn nguồn dinh dưỡng tự nhiên, đa dạng.",
                            MetaKeyword = "MIX hạt cao cấp",
                            MetaTitle = "MIX hạt cao cấp",
                            Name = "MIX hạt cao cấp",
                            OriginalPrice = 170000.0,
                            Price = 160000.0,
                            SeoAlias = "mix-hat-cao-cap",
                            Sku = "MIX01",
                            Status = 1,
                            UrlCode = "mix-hat-cao-cap"
                        },
                        new
                        {
                            Id = new Guid("deebff1d-3097-46f3-b299-b7025c6688a7"),
                            CategoryId = new Guid("d3a7f832-fb28-4458-97b4-90d0bb61b622"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9245),
                            Description = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay. Mix 6 loại hạt gồm Óc chó đỏ, Hạnh Nhân, Hạt điều, Óc chó vàng, Macca, Bí xanh mang đến cho bạn nguồn dinh dưỡng tự nhiên, đa dạng. ",
                            Discount = 10000.0,
                            DisplayName = "MIX 6 hạt dinh dưỡng",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt dinh dưỡng được hiểu một cách đơn giản là các loại hạt có vỏ cứng và tách vỏ khi dùng như hạt hạnh nhân, óc chó, điều, bí xanh…Những loại hạt này cung cấp cho cơ thể nhiều dưỡng chất cần thiết và được sử dụng rất nhiều để ăn kiêng, ăn chay. Mix 6 loại hạt gồm Óc chó đỏ, Hạnh Nhân, Hạt điều, Óc chó vàng, Macca, Bí xanh mang đến cho bạn nguồn dinh dưỡng tự nhiên, đa dạng.",
                            MetaKeyword = "MIX 6 loại hạt dinh dưỡng",
                            MetaTitle = "MIX 6 loại hạt dinh dưỡng",
                            Name = "MIX 6 hạt dinh dưỡng",
                            OriginalPrice = 160000.0,
                            Price = 150000.0,
                            SeoAlias = "mix-6-loai-hat-dinh-duong",
                            Sku = "MIX02",
                            Status = 1,
                            UrlCode = "mix-6-loai-hat-dinh-duong"
                        },
                        new
                        {
                            Id = new Guid("42fe6086-ea71-4c84-8197-bc72cb2eaba6"),
                            CategoryId = new Guid("0e6b14eb-242d-46ec-b90b-75559c14df26"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9248),
                            Description = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột...",
                            Discount = 5000.0,
                            DisplayName = "Hạnh nhân rang bơ",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = true,
                            MetaDescription = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột...",
                            MetaKeyword = "Hạnh nhân rang bơ",
                            MetaTitle = "Hạnh nhân rang bơ",
                            Name = "Hạnh nhân rang bơ",
                            OriginalPrice = 130000.0,
                            Price = 125000.0,
                            SeoAlias = "hanh-nhan-rang-bo",
                            Sku = "H01",
                            Status = 1,
                            UrlCode = "hanh-nhan-rang-bo"
                        },
                        new
                        {
                            Id = new Guid("3cc41fff-3203-441b-acfc-6273def75b42"),
                            CategoryId = new Guid("0e6b14eb-242d-46ec-b90b-75559c14df26"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9255),
                            Description = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột...",
                            Discount = 5000.0,
                            DisplayName = "Hạnh nhân sấy",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạnh nhân có nguồn gốc từ Trung Đông. Hạnh nhân được bán sống hoặc rang. Chúng cũng được sử dụng để sản xuất sữa hạnh nhân, dầu, bơ, bột...",
                            MetaKeyword = "Hạnh nhân sấy",
                            MetaTitle = "Hạnh nhân sấy",
                            Name = "Hạnh nhân sấy",
                            OriginalPrice = 135000.0,
                            Price = 130000.0,
                            SeoAlias = "hanh-nhan-say",
                            Sku = "H02",
                            Status = 1,
                            UrlCode = "hanh-nhan-say"
                        },
                        new
                        {
                            Id = new Guid("4e254c2a-9083-49dd-93f0-cc86f78502bc"),
                            CategoryId = new Guid("2ba2070c-d658-4348-a490-d22c1baaed75"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9259),
                            Description = "Hạt óc chó đỏ là loại hạt óc chó không biến đổi Gen được tạo ra bằng phương pháp lai tạo tự nhiên. Sở dĩ được gọi là hạt óc chó đỏ bởi vì sau khi tách lớp vỏ cứng bên ngoài thì nhân bên trong có một lớp vỏ lụa màu đỏ, thịt bên trong nhân là màu trắng sữa.",
                            Discount = 10000.0,
                            DisplayName = "Hạt óc chó đỏ",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = true,
                            MetaDescription = "Hạt óc chó đỏ là loại hạt óc chó không biến đổi Gen được tạo ra bằng phương pháp lai tạo tự nhiên. Sở dĩ được gọi là hạt óc chó đỏ bởi vì sau khi tách lớp vỏ cứng bên ngoài thì nhân bên trong có một lớp vỏ lụa màu đỏ, thịt bên trong nhân là màu trắng sữa.",
                            MetaKeyword = "Hạt óc chó đỏ",
                            MetaTitle = "Hạt óc chó đỏ",
                            Name = "Hạt óc chó đỏ",
                            OriginalPrice = 160000.0,
                            Price = 150000.0,
                            SeoAlias = "hanh-nhan-say",
                            Sku = "O01",
                            Status = 1,
                            UrlCode = "oc-cho-do"
                        },
                        new
                        {
                            Id = new Guid("3aeb1881-6bc5-4ffa-9a8e-eabf2ca215e1"),
                            CategoryId = new Guid("2ba2070c-d658-4348-a490-d22c1baaed75"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9262),
                            Description = "Hạt óc chó vàng là loại hạt óc chó được trồng thông dụng nhất hiện nay tại Mỹ, Úc, Anh, Trung Quốc… Sở dĩ gọi là hạt óc chó vàng bởi vì sau khi tách lớp vỏ cứng bên ngoài thì nhân bên trong có một lớp vỏ lụa màu vàng, thịt bên trong nhân là màu trắng sữa.",
                            Discount = 10000.0,
                            DisplayName = "Hạt óc chó vàng",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = true,
                            MetaDescription = "Hạt óc chó vàng là loại hạt óc chó được trồng thông dụng nhất hiện nay tại Mỹ, Úc, Anh, Trung Quốc… Sở dĩ gọi là hạt óc chó vàng bởi vì sau khi tách lớp vỏ cứng bên ngoài thì nhân bên trong có một lớp vỏ lụa màu vàng, thịt bên trong nhân là màu trắng sữa.",
                            MetaKeyword = "Hạt óc chó vàng",
                            MetaTitle = "Hạt óc chó vàng",
                            Name = "Hạt óc chó vàng",
                            OriginalPrice = 120000.0,
                            Price = 110000.0,
                            SeoAlias = "oc-cho-vang",
                            Sku = "O02",
                            Status = 1,
                            UrlCode = "oc-cho-vang"
                        },
                        new
                        {
                            Id = new Guid("5875eb00-05d2-4ee9-98c4-277ba5474d39"),
                            CategoryId = new Guid("6c5d6237-94b0-47bb-9f2c-1f4d89e74043"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9267),
                            Description = "Granola là món ăn quen thuộc của người Mỹ vào buổi sáng, đây là hỗn hợp của nhiều thực phẩm lành lạnh với hàm lượng chất dinh dưỡng cao, nhất là giàu protein. Granola gồm các loại hạt dinh dưỡng, trái cây khô, yến mạch,…. được sấy giòn, giữ được 100% hương vị tươi ngon tự nhiên.",
                            Discount = 10000.0,
                            DisplayName = "Granola",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = true,
                            MetaDescription = "Granola là món ăn quen thuộc của người Mỹ vào buổi sáng, đây là hỗn hợp của nhiều thực phẩm lành lạnh với hàm lượng chất dinh dưỡng cao, nhất là giàu protein. Granola gồm các loại hạt dinh dưỡng, trái cây khô, yến mạch,…. được sấy giòn, giữ được 100% hương vị tươi ngon tự nhiên.",
                            MetaKeyword = "Granola",
                            MetaTitle = "Granola",
                            Name = "Granola",
                            OriginalPrice = 130000.0,
                            Price = 120000.0,
                            SeoAlias = "granola",
                            Sku = "G01",
                            Status = 1,
                            UrlCode = "granola"
                        },
                        new
                        {
                            Id = new Guid("e0638d29-bc83-4104-8161-e76b4a952145"),
                            CategoryId = new Guid("030bfb43-c2d2-4921-9cdf-6109caa104cb"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9270),
                            Description = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            Discount = 10000.0,
                            DisplayName = "Hạt điều xếp hoa",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = true,
                            MetaDescription = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            MetaKeyword = "Hạt điều rang muối xếp hoa",
                            MetaTitle = "Hạt điều rang muối xếp hoa",
                            Name = "Hạt điều xếp hoa",
                            OriginalPrice = 130000.0,
                            Price = 120000.0,
                            SeoAlias = "hat-dieu-rang-muoi-xep-hoa",
                            Sku = "D01",
                            Status = 1,
                            UrlCode = "hat-dieu-rang-muoi-xep-hoa"
                        },
                        new
                        {
                            Id = new Guid("7b4186af-bf18-494c-a941-8c6b1ecc33a0"),
                            CategoryId = new Guid("030bfb43-c2d2-4921-9cdf-6109caa104cb"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9274),
                            Description = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            Discount = 10000.0,
                            DisplayName = "Hạt điều sấy",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            MetaKeyword = "Hạt điều sấy",
                            MetaTitle = "Hạt điều sấy",
                            Name = "Hạt điều sấy",
                            OriginalPrice = 130000.0,
                            Price = 120000.0,
                            SeoAlias = "hat-dieu-sấy",
                            Sku = "D03",
                            Status = 1,
                            UrlCode = "hat-dieu-sấy"
                        },
                        new
                        {
                            Id = new Guid("6018769a-736d-40b8-9d5d-8a69b42877a9"),
                            CategoryId = new Guid("030bfb43-c2d2-4921-9cdf-6109caa104cb"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9277),
                            Description = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            Discount = 5000.0,
                            DisplayName = "Hạt điều lon pet",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            MetaKeyword = "Hạt điều lon pet",
                            MetaTitle = "Hạt điều lon pet",
                            Name = "Hạt điều lon pet",
                            OriginalPrice = 140000.0,
                            Price = 135000.0,
                            SeoAlias = "hat-dieu-lon-pet",
                            Sku = "D02",
                            Status = 1,
                            UrlCode = "hat-dieu-lon-pet"
                        },
                        new
                        {
                            Id = new Guid("cf229b93-7d33-406c-af26-53633d301a19"),
                            CategoryId = new Guid("7e6e5f6f-9f18-42fb-91ff-418e09261fb4"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9281),
                            Description = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            Discount = 10000.0,
                            DisplayName = "Bánh hạt điều",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = true,
                            MetaDescription = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            MetaKeyword = "Bánh hạt điều",
                            MetaTitle = "Bánh hạt điều",
                            Name = "Bánh hạt điều",
                            OriginalPrice = 90000.0,
                            Price = 80000.0,
                            SeoAlias = "banh-hat-dieu",
                            Sku = "B01",
                            Status = 1,
                            UrlCode = "banh-hat-dieu"
                        },
                        new
                        {
                            Id = new Guid("18495028-3944-4d00-b2af-9292a6b2dcaa"),
                            CategoryId = new Guid("7e6e5f6f-9f18-42fb-91ff-418e09261fb4"),
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9287),
                            Description = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            Discount = 10000.0,
                            DisplayName = "Bánh rong biển kẹp hạt",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            MetaDescription = "Hạt điều là hạt thuộc họ Anacardium occidentale có nguồn gốc từ Brazil được trồng nhiều ở các tỉnh phía Nam của Việt Nam. Ngoài hương vị thơm ngon thì hạt điều còn có giá trị dinh dưỡng cao cùng với những công dụng tuyệt vời đối với sức khỏe con người.",
                            MetaKeyword = "Bánh rong biển kẹp hạt",
                            MetaTitle = "Bánh rong biển kẹp hạt",
                            Name = "Bánh rong biển kẹp hạt",
                            OriginalPrice = 170000.0,
                            Price = 160000.0,
                            SeoAlias = "banh-rong-bien-kep-hat",
                            Sku = "B02",
                            Status = 1,
                            UrlCode = "banh-rong-bien-kep-hat"
                        });
                });

            modelBuilder.Entity("Core.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4440468f-f4e4-4ade-8014-5744a5eff0fc"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9352),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("6fe5001c-0cc9-4873-a826-81676479ec52"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/nhanvo_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("c4b9964d-79f7-4336-adf8-4743fac2ee56"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9357),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("6fe5001c-0cc9-4873-a826-81676479ec52"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/nhanvo_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("0d8bd15c-4926-4476-a771-2e8027dc116f"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9360),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("6fe5001c-0cc9-4873-a826-81676479ec52"),
                            SortOrder = 4,
                            Status = 1,
                            Url = "/images/nhanvo_03.jpg"
                        },
                        new
                        {
                            Id = new Guid("a2acea8f-6f37-4dd3-87f5-7484a1acd14e"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9362),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("6fe5001c-0cc9-4873-a826-81676479ec52"),
                            SortOrder = 4,
                            Status = 1,
                            Url = "/images/nhanvo_04.jpg"
                        },
                        new
                        {
                            Id = new Guid("e057e570-813a-4569-aee8-6b7d37090740"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9367),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("31b72883-ee9d-45b7-9770-51f4d7d2ba2f"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/nhannguyen_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("8a804d4c-539a-45f1-bb4d-660b0dc57c09"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9370),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("31b72883-ee9d-45b7-9770-51f4d7d2ba2f"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/nhannguyen_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("fee79c1e-2e01-4bc4-9632-af2199e4550c"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9372),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("31b72883-ee9d-45b7-9770-51f4d7d2ba2f"),
                            SortOrder = 3,
                            Status = 1,
                            Url = "/images/nhannguyen_03.jpg"
                        },
                        new
                        {
                            Id = new Guid("f3a39995-f182-4b4a-a10e-4dbd5197d58a"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9375),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("31b72883-ee9d-45b7-9770-51f4d7d2ba2f"),
                            SortOrder = 4,
                            Status = 1,
                            Url = "/images/nhannguyen_04.jpg"
                        },
                        new
                        {
                            Id = new Guid("f7fbe196-8bdf-48aa-8fe4-1076b87f8d1f"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9379),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("c09653ee-9781-4b47-b1b9-23975c147bc5"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/nutvo_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("97ebb7e0-bd66-457b-a21c-e4207f0365ce"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9382),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("c09653ee-9781-4b47-b1b9-23975c147bc5"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/nutvo_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("08598ca8-1126-460a-b2af-b0ae3bdf0ec9"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9384),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("4f4055a6-eb23-41c5-b885-1672c207e273"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/nutvolon_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("61a0fe7f-1ec4-47db-8d6a-c67bbe7c4af4"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9387),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("4f4055a6-eb23-41c5-b885-1672c207e273"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/nutvolon_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("0a44ed2a-d49e-4704-949c-c2f32947b91e"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9391),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("02306207-f983-4bcc-b7ec-70221cee8dc7"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/mix_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("6dd8fdff-19ed-4da2-ba38-143bd549042c"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9394),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("deebff1d-3097-46f3-b299-b7025c6688a7"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/mixcc_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("a063a6eb-826d-44ec-85c2-c67f569f758b"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9396),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("deebff1d-3097-46f3-b299-b7025c6688a7"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/mix_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("1e7052a5-dc4d-4039-b484-2a275bb46fa6"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9399),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("3cc41fff-3203-441b-acfc-6273def75b42"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/hanhnhan_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("c749cd4e-9c35-44d6-b6b6-804ad7919713"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9403),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("3cc41fff-3203-441b-acfc-6273def75b42"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/hanhnhan_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("f9d89a63-9a03-4a06-8372-ac0ce649aaa0"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9406),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("3cc41fff-3203-441b-acfc-6273def75b42"),
                            SortOrder = 3,
                            Status = 1,
                            Url = "/images/hanhnhan_03.jpg"
                        },
                        new
                        {
                            Id = new Guid("9bc06aaf-b62f-416c-8848-84780a7bc627"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9408),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("42fe6086-ea71-4c84-8197-bc72cb2eaba6"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/hanhnhan_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("78dde65a-3184-4aaa-8305-ee630c0a5fb2"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9411),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("42fe6086-ea71-4c84-8197-bc72cb2eaba6"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/hanhnhan_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("b88cef82-538d-4b55-8e16-8011e79cfd36"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9415),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("42fe6086-ea71-4c84-8197-bc72cb2eaba6"),
                            SortOrder = 3,
                            Status = 1,
                            Url = "/images/hanhnhan_03.jpg"
                        },
                        new
                        {
                            Id = new Guid("46446d1f-67f9-479b-8bc2-af2bc92f3292"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9418),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("4e254c2a-9083-49dd-93f0-cc86f78502bc"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/occhodo_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("6fe6cc1c-4ddd-4684-a554-0d117cc596a1"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9420),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("4e254c2a-9083-49dd-93f0-cc86f78502bc"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/occhodo_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("1d14c9bf-93a3-4cc1-ae93-5985eaf81957"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9464),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("3aeb1881-6bc5-4ffa-9a8e-eabf2ca215e1"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/occhovang_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("537e1bb9-2ff6-4bc4-a11a-fdd1481ea252"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9469),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("3aeb1881-6bc5-4ffa-9a8e-eabf2ca215e1"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/occhovang_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("fd7f3a72-612b-49ad-be1f-6e44ee69064a"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9472),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("5875eb00-05d2-4ee9-98c4-277ba5474d39"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/granola_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("4e5ab9fe-8058-47e3-85cf-79ad07bcfd76"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9474),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("5875eb00-05d2-4ee9-98c4-277ba5474d39"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/granola_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("2439a6bb-0eb3-4d6c-b726-483d37f43b8e"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9477),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("5875eb00-05d2-4ee9-98c4-277ba5474d39"),
                            SortOrder = 3,
                            Status = 1,
                            Url = "/images/granola_03.jpg"
                        },
                        new
                        {
                            Id = new Guid("c260f5fe-ae95-4d66-ada4-7c3d0063bcf0"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9481),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("6018769a-736d-40b8-9d5d-8a69b42877a9"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/dieupet_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("c3a5e39b-b268-4591-bc81-7874935ef8ef"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9483),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("7b4186af-bf18-494c-a941-8c6b1ecc33a0"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/dieusay_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("9b71006d-73fa-4b66-84c1-8d4d8e365e89"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9486),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("e0638d29-bc83-4104-8161-e76b4a952145"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/dieuxephoa_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("5fd6f001-d42f-4c3c-8379-774459f58b55"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9488),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("cf229b93-7d33-406c-af26-53633d301a19"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/banhdieu_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("cd07005a-f2c7-4935-a575-cd4e5f0a5979"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9493),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("cf229b93-7d33-406c-af26-53633d301a19"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/banhdieu_02.jpg"
                        },
                        new
                        {
                            Id = new Guid("0ef3e1b8-bba0-431c-b9db-7213c12d8008"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9495),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("cf229b93-7d33-406c-af26-53633d301a19"),
                            SortOrder = 3,
                            Status = 1,
                            Url = "/images/banhdieu_03.jpg"
                        },
                        new
                        {
                            Id = new Guid("73e60cad-ba66-4d41-a7b0-521cf9bf09f0"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9497),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("cf229b93-7d33-406c-af26-53633d301a19"),
                            SortOrder = 3,
                            Status = 1,
                            Url = "/images/banhdieu_03.jpg"
                        },
                        new
                        {
                            Id = new Guid("cbbc9644-113c-4854-bbed-df0b886f0226"),
                            Caption = "Thumb Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9500),
                            FileSize = 0L,
                            IsDefault = false,
                            ProductId = new Guid("18495028-3944-4d00-b2af-9292a6b2dcaa"),
                            SortOrder = 1,
                            Status = 1,
                            Url = "/images/banhrong_01.jpg"
                        },
                        new
                        {
                            Id = new Guid("6d4e78c4-4da5-4133-9b9a-f29b79062ac1"),
                            Caption = "Main Image",
                            CreatedOn = new DateTime(2023, 9, 11, 7, 2, 47, 849, DateTimeKind.Utc).AddTicks(9504),
                            FileSize = 0L,
                            IsDefault = true,
                            ProductId = new Guid("18495028-3944-4d00-b2af-9292a6b2dcaa"),
                            SortOrder = 2,
                            Status = 1,
                            Url = "/images/banhrong_02.jpg"
                        });
                });

            modelBuilder.Entity("Core.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("sizes", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Slide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("slides", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.ProductImage", b =>
                {
                    b.HasOne("Core.Entities.Product", null)
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Core.Entities.Size", b =>
                {
                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
